# Generated by Django 4.1.7 on 2023-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0003_customuser_phone_subuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subuser',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
