# Generated by Django 4.1.7 on 2023-02-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0004_customuser_height_subuser_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subuser',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
