# Generated by Django 4.1.7 on 2023-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0005_customuser_is_selected_subuser_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='', upload_to='media/images')),
                ('image', models.ImageField(default='', upload_to='media/images')),
                ('discount', models.CharField(max_length=50)),
            ],
        ),
    ]
