# Generated by Django 4.1.7 on 2023-02-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0009_customuser_body_size_subuser_body_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='body_size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='body_size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='height',
            field=models.CharField(default='', max_length=50),
        ),
    ]
