# Generated by Django 4.1.7 on 2023-03-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0013_alter_productimg_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='backgroungimage',
            field=models.ImageField(default='', upload_to='media/bg/images'),
        ),
        migrations.AddField(
            model_name='category',
            name='hidden_image',
            field=models.ImageField(default='', upload_to='media/hidden/images'),
        ),
    ]
