# Generated by Django 4.1.7 on 2023-03-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0014_remove_brand_discount_remove_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='media/slider1/images'),
        ),
    ]
