# Generated by Django 4.1.7 on 2023-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0015_product_color_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('man', 'MAN'), ('woman', 'WOMAN'), ('boy', 'BOY'), ('girl', 'GIRL'), ('baby_boy', 'BABT_BOY'), ('baby_girl', 'BABY_GIRL')], default='man', max_length=20),
        ),
    ]
