# Generated by Django 4.1.7 on 2023-03-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0016_category_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('man', 'MAN'), ('woman', 'WOMAN'), ('boy', 'BOY'), ('girl', 'GIRL'), ('babyBoy', 'BABT_BOY'), ('babyGirl', 'BABY_GIRL')], default='man', max_length=20),
        ),
    ]
