# Generated by Django 4.1.7 on 2023-03-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0017_alter_category_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_now',
            field=models.CharField(default='', max_length=255),
        ),
    ]
