# Generated by Django 4.1.7 on 2023-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroineapp', '0018_product_buy_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
